var __certmanagesub=function(a){var y=function(h){function u(a){if(!a)return alert("UI load error."),!1;var c=document.createElement("div");document.body.insertBefore(c,document.body.firstChild);c.innerHTML=a;return!0}function l(b){if(!b)return!1;var c=a.loadUI("certview")({type:null,args:{type:k,idx:m,cert:d},onConfirm:function(){c.dispose();b.focus()},onCancel:function(){c.dispose();b.focus()}});c.show();return!0}function e(b,c){if(!b||!c)return!1;Dialog=a.loadUI("changepassword")({type:null,args:null,
onConfirm:function(d,e){if(null==d||0>=d.length||null==e||0>=e.length)return!1;try{var f=parseInt(m),g=a.PFUC[f],q,n;q=n=null;var p=a.usWebToolkit.pkcs8.encryptedPrivateKeyFromBase64(g.signpri),l=a.usWebToolkit.pkcs8.checkUserCertPassword(p,d);if(!1===l){var p=null,x={code:-1,message:c.IDS_MSGBOX_PW_ERROR_INPUT_WRONG_PASSWORD};throw x;}q=a.usWebToolkit.pkcs8.changePassword(p,d,e,"Base64");p=null;if("undefined"!==typeof g.kmcert){p=a.usWebToolkit.pkcs8.encryptedPrivateKeyFromBase64(g.kmpri);l=a.usWebToolkit.pkcs8.checkUserCertPassword(p,
d);if(!1===l)throw p=null,x={code:-1,message:c.IDS_MSGBOX_PW_ERROR_INPUT_WRONG_PASSWORD},x;n=a.usWebToolkit.pkcs8.changePassword(p,d,e,"Base64")}p=null;try{f={},f.signcert=g.signcert,f.signpri=q,null!==n&&(f.kmcert=g.kmcert,f.kmpri=n),a.PFSH.SaveUserCert(g.ca,f,document.domain,!1),g=f=null,h.onConfirm(!0),a.uiUtil().msgBox(c.IDS_MSGBOX_CERT_CHANGE_PW_SUCCESS)}catch(r){switch(console.log("***** SANDBOX.PFSH.SaveUserCert *****"),console.log("e.code : ",r.code,"e.message : ",r.message,"e.detail : ",
r.detail),r.code){case 1E7:0<=r.detail.indexOf("115010")?a.uiUtil().msgBox(c.IDS_MSGBOX_PW_ERROR_PASSWORD_IS_NOT_MATCHED):a.uiUtil().errMsgBox(c.IDS_MSGBOX_CERT_CHANGE_PW_ERROR,r.detail);break;default:a.uiUtil().errMsgBox(c.IDS_MSGBOX_CERT_CHANGE_PW_ERROR,r.code);break}}finally{}}catch(k){console.log("***** ChangePW error *****"),console.log("Err Code : ",k.code,"\nErr Msg : ",k.message),a.uiUtil().errMsgBox(k.message,k.code)}d=e="";Dialog.dispose();setTimeout(function(){b.focus()},10)},onCancel:function(){Dialog.dispose();
setTimeout(function(){b.focus()},10)}});Dialog.show();return!0}function s(b,c){if(!b||!c)return!1;confirm(c.IDS_CONFIRMBOX_WARNING_DELETE_CERT)?(Dialog=a.loadUI("password")({type:null,args:null,onConfirm:function(d){if(null==d||0>=d.length)return!1;try{var e=parseInt(m),f=a.usWebToolkit.pkcs8.encryptedPrivateKeyFromBase64(a.PFUC[e].signpri),g=a.usWebToolkit.pkcs8.checkUserCertPassword(f,d),f="";if(!1===g)a.uiUtil().msgBox(c.IDS_MSGBOX_PW_ERROR_INPUT_WRONG_PASSWORD);else try{a.PFSH.DeleteUserCertByIndex(e,
document.domain),h.onConfirm(!0),a.uiUtil().msgBox(c.IDS_MSGBOX_CERT_DELETE_SUCCESS)}catch(k){console.log("***** DeleteUserCertByIndex error *****"),console.log("e.code : ",k.code,"e.message : ",k.message,"e.detail : ",k.detail),a.uiUtil().errMsgBox(c.IDS_MSGBOX_CERT_DELETE_ERROR,k.code)}}catch(n){console.log("***** CheckUserCertPassword error *****"),console.log("Err Code : ",n.code,"\nErr Msg : ",n.message),a.uiUtil().errMsgBox(n.message,n.code)}d="";Dialog.dispose();setTimeout(function(){b.focus()},
10)},onCancel:function(){Dialog.dispose();setTimeout(function(){b.focus()},10)}}),Dialog.show()):b.focus();return!0}var z=function(){var b;b=window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("MSXML2.XMLHTTP.3.0");b.open("GET",a.ESVS.SRCPath+"unisignweb/rsrc/layout/mobile/m_certmanagesub.html?version="+a.ver,!1);b.send(null);return b.responseText},t=function(){var b;b=window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("MSXML2.XMLHTTP.3.0");b.open("GET",a.ESVS.SRCPath+
"unisignweb/rsrc/lang/certmanage_"+a.ESVS.Language+".js?version="+a.ver,!1);b.send(null);return b.responseText},g=a.ESVS.TabIndex,k=h.args.type,m=h.args.idx,d=h.args.cert;return function(){var b=eval(z),c=eval(eval(t)());u(b());document.getElementById("m-us-lbl-cert-manage-sub-title").appendChild(document.createTextNode(c.IDS_CERT_MANAGEMENT));if(null!==m&&null!==d){a.usWebToolkit.x509Certificate.parser(d,k);var v=a.usWebToolkit.x509Certificate.getCertificatePoliciesOid(),w=a.usWebToolkit.x509Certificate.getSubjectName(),
f=a.usWebToolkit.x509Certificate.getNotAfter(),b=a.certUtil().getIssuerName(v);"undefined"==b&&(b=a.certUtil().getO(w));var w=a.certUtil().getCN(w),v=a.certUtil().getCertType(v),y=a.certUtil().getLocalDate(f),f=a.certUtil().getExpirationStateValue(f),q=document.getElementById("m-us-img-cert-manage-sub");if(0===f)q.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_cert_valid_small.png",0);else if(1===f)q.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_cert_valid_1_month_small.png",
0);else if(2===f)q.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_cert_invalid_small.png",0);else return;f=document.getElementById("m-us-div-cert-manage-sub-info").getElementsByTagName("span");f[0].appendChild(document.createTextNode(w));f[1].appendChild(document.createTextNode(c.IDS_CERT_ISSUER));f[2].appendChild(document.createTextNode(b));f[3].appendChild(document.createTextNode(c.IDS_CERT_CLASSIFY));f[4].appendChild(document.createTextNode(v));f[5].appendChild(document.createTextNode(c.IDS_CERT_EXPIRATION_DAY));
f[6].appendChild(document.createTextNode(y))}b=document.getElementById("m-us-cert-manage-sub-cert-view-btn");b.setAttribute("value",c.IDS_CERT_VIEW,0);b.setAttribute("title",c.IDS_CERT_VIEW+c.IDS_BUTTON,0);b.setAttribute("tabindex",g,0);b.onclick=function(){l(this)};b=document.getElementById("m-us-cert-manage-sub-pw-change-btn");b.setAttribute("value",c.IDS_PW_CHANGE,0);b.setAttribute("title",c.IDS_PW_CHANGE+c.IDS_BUTTON,0);b.setAttribute("tabindex",g+1,0);b.onclick=function(){e(this,c)};b=document.getElementById("m-us-cert-manage-sub-cert-copy-btn");
b.setAttribute("value",c.IDS_CERT_COPY,0);b.setAttribute("title",c.IDS_CERT_COPY+c.IDS_BUTTON,0);b.setAttribute("tabindex",g+2,0);b.onclick=function(){};b.readOnly=!0;b.disabled=!0;b=document.getElementById("m-us-cert-manage-sub-cert-delete-btn");b.setAttribute("value",c.IDS_CERT_DELETE,0);b.setAttribute("title",c.IDS_CERT_DELETE+c.IDS_BUTTON,0);b.setAttribute("tabindex",g+3,0);b.onclick=function(){s(this,c)};b=document.getElementById("m-us-cert-manage-sub-put-cert-out-btn");b.setAttribute("value",
c.IDS_CERT_PUT_OUT,0);b.setAttribute("title",c.IDS_CERT_PUT_OUT+c.IDS_BUTTON,0);b.setAttribute("tabindex",g+4,0);b.onclick=function(){a:if(this&&c){var b=null,d=null,f=null;try{b=a.PFSH.GetP12ForBuToMo(parseInt(m),"hex"),d=b.key,f=b.p12}catch(e){console.log("***** GetP12ForBuToMo error *****");console.log("e.code : ",e.code,"e.message : ",e.message,"e.detail : ",e.detail);a.uiUtil().errMsgBox(c.IDS_MSGBOX_CERT_EXPORT_ERROR,e.code);break a}try{b="default";"android"===a.osName?"android samsung"===a.browserName||
"android lg"===a.browserName||"android browser"===a.browserName?b="default":"android chrome"===a.browserName&&(b="chrome"):"ios"==a.osName&&("ios safari"===a.browserName?b="default":"ios chrome"===a.browserName&&(b="googlechrome"));var g=window.location.href.split(/[?#]/)[0],k=g.lastIndexOf("/"),g=g.substr(0,k+1)+a.ESVS.SRCPath+"unisignweb/rsrc/layout/mobile/w2a/m_exportcertresult.html";UniSignW2A.backupStore(g,b,f,d,"0","recall")}catch(h){alert("failure\ne : "+h)}}};b=document.getElementById("m-us-cert-manage-sub-ccl-btn");
b.setAttribute("value",c.IDS_CERT_CANCEL,0);b.setAttribute("title",c.IDS_CERT_CANCEL+c.IDS_BUTTON,0);b.setAttribute("tabindex",g+5,0);b.onclick=function(){h.onCancel()};b=document.getElementById("m-us-cert-manage-sub-cls-btn-img");b.setAttribute("alt",c.IDS_PASSWORD_CLOSE,0);b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_x-btn.png",0);b=document.getElementById("m-us-cert-manage-sub-cls-btn");b.setAttribute("tabindex",g+7,0);b.onclick=function(){h.onCancel()};return document.getElementById("m-us-div-cert-manage-sub")}()};
return function(h){var u=a.uiLayerLevel,l=a.uiUtil().getOverlay(u),e=y({type:h.type,args:h.args,onConfirm:h.onConfirm,onCancel:h.onCancel,onTerminate:h.onTerminate});e.style.zIndex=u+1;a.ESVS.TargetObj.insertBefore(l,a.ESVS.TargetObj.firstChild);var s=window.onorientationchange;return{show:function(){l.style.display="block";var h=a.uiUtil().getNumSize(a.uiUtil().getStyle(e,"height","height")),h=-1===h?a.uiUtil().getScrollTop()+a.uiUtil().getViewportHeight()/6:a.uiUtil().getScrollTop()+(a.uiUtil().getViewportHeight()-
h)/3;e.style.top=0>h?"0px":h+"px";e.style.left=a.uiUtil().getScrollLeft()+(a.uiUtil().getViewportWidth()-a.uiUtil().getNumSize(a.uiUtil().getStyle(e,"width","width")))/2+"px";e.style.display="block";var t=0,g=0,k=0,m=0;0==window.orientation||180==window.orientation?(t=a.uiUtil().getViewportWidth(),g=a.uiUtil().getViewportHeight()):(k=a.uiUtil().getViewportWidth(),m=a.uiUtil().getViewportHeight());window.addEventListener("orientationchange",function(){var d=0,b=0;"android chrome"==a.browserName||"unknown"==
a.browserName?0==window.orientation||180==window.orientation?0<t?(d=t,b=g):(d=m+87,b=k-40):0<k?(d=k,b=m):(d=g+87,b=t-40):(d=a.uiUtil().getViewportWidth(),b=a.uiUtil().getViewportHeight());var c=a.uiUtil().getNumSize(a.uiUtil().getStyle(e,"width","width"));-1<c&&(d=a.uiUtil().getScrollLeft()+(d-c)/2+"px",e.style.left=d);d=a.uiUtil().getNumSize(a.uiUtil().getStyle(e,"height","height"));b=-1===d?a.uiUtil().getScrollTop()+b/6:a.uiUtil().getScrollTop()+(b-d)/3;e.style.top=b+"px";s&&s()});a.uiLayerLevel+=
10;a.ESVS.TabIndex+=30;setTimeout(function(){var a=e.getElementsByTagName("input");if(0<a.length)for(var b=0;b<a.length;b++)"m-us-cert-manage-sub-cert-view-btn"==a[b].id&&a[b].focus()},10)},hide:function(){l.style.display="none";e.style.display="none"},dispose:function(){window.addEventListener("orientationchange",function(){s&&s()});e.parentNode.parentNode.removeChild(e.parentNode);l.parentNode.removeChild(l);a.uiLayerLevel-=10;a.ESVS.TabIndex-=30}}}};
