var __certmanage=function(a){var A=function(g){function m(b){if(!a.certsList||!b)return null;for(var c=null,c=a.certsList,e=c.list.length,h=[],d=0,l=0;l<e;l++){a.usWebToolkit.x509Certificate.parser(c.list[l].cert,"Base64");var k=a.usWebToolkit.x509Certificate.getCertificatePoliciesOid(),r=a.usWebToolkit.x509Certificate.getSubjectName(),m=a.usWebToolkit.x509Certificate.getNotAfter(),x=a.usWebToolkit.x509Certificate.getNotAfter(),y=c.list[l].index,g=a.certUtil().getIssuerName(k);"undefined"==g&&(g=
a.certUtil().getO(r));var f=[];f[0]=a.certUtil().getCertType(k);f[1]=b.IDS_CERT_EXPIRATION_DAY+" ";f[2]=a.certUtil().getLocalDate(m);f[3]=a.certUtil().getCN(r);f[4]=g;f[5]=y;f[6]=a.certUtil().getExpirationStateValue(x);h[d++]=f}return c={list:h}}function f(b,c,e,h){if(a.CONST.__USFB_M_DISK.device>b||0>c||!e)return-1;e=c=0;a.certsList&&(a.certsList=null);if(a.CONST.__PF_M_LS.device===b&&2&a.ESVS.Mode){if(!a.PFSH)return-1;try{a.PFSH.SelectStorage(1)}catch(d){p.log("***** Plugin Free SelectStorage error *****"),
p.log("e.code : ",d.code,"e.message : ",d.message,"e.detail : ",d.detail)}try{a.PFSH.LoadAllCerts(document.domain)}catch(l){301E5===l.code?(a.PFSH.InstallCACerts(document.domain),a.PFSH.LoadAllCerts(document.domain)):(p.log("***** Plugin Free LoadAllCerts error *****"),p.log("e.code : ",l.code,"e.message : ",l.message,"e.detail : ",l.detail))}b=null;try{b=a.PFSH.GetUserCerts(document.domain),a.PFUC=b}catch(k){p.log("***** Plugin Free GetUserCerts error *****"),p.log("e.code : ",k.code,"e.message : ",
k.message,"e.detail : ",k.detail)}b&&(c=b.length-1);p.log("***** Plugin Free *****");p.log("user certificate counts : ",c);if(0<c){h=[];for(var r=0;r<c;r++){var m=r+1,f={};f.index=m;f.cert=b[m].signcert;h[r]=f}a.certsList={list:h}}else a.certsList=null,e=0}return e}function s(b){if(!b)return!1;var c=a.loadUI("swinfo")({type:null,args:null,onConfirm:function(){c.dispose();b.focus()},onCancel:function(){c.dispose();b.focus()}});c.show();return!0}function z(b){if(!b)return!1;var c=f(w,0,b,"");0!=c&&
a.uiUtil().errMsgBox(b.IDS_MSGBOX_COMMON_ERROR_GET_CERT,c);c=m(b);x=a.loadUI("certlist");k=x({listtype:"mobilecertmanage",bodyid:"m-us-div-cert-manage-list-inner",rowid:"m-us-mobile-cert-manage-cert-list-row",imgid:"m-us-mobile-cert-manage-cert-status-img",eleid:"m-us-mobile-cert-manage-cert-data-element",confirm:function(a){a&&(f(w,0,b,""),(a=m(b))?k.redrawList(a.list,a.list.length):k.redrawList(null,0))},cancel:function(){}});c?k.drawList(c.list,c.list.length,q++):k.drawList(null,0,q++);return!0}
function t(b){if(null==b||void 0==b)return!1;var c=!a.uiUtil().isItSupportingThisStorage(b);!1==c&&null!=a.ESVS.Media&&null!=a.ESVS.Media.list&&0>a.ESVS.Media.list.indexOf(b.name)&&(c=!0);if(c)return!1;var c=document.getElementById("m-us-cert-manage-storage-btn-list"),e=document.createElement("li");e.setAttribute("id","m-us-cert-manage-storage-btn-li-"+b.name,0);e.setAttribute("mediaIndex",b.mediaIndex,0);5==b.mediaIndex&&(e.className="line-first");"hidden"===b.visibility?(e.style.display="none",
e.style.visibility="hidden"):(e.style.display="block",e.style.visibility="visible");var h=document.createElement("button");h.setAttribute("type","button",0);h.setAttribute("id","m-us-cert-manage-btn-"+b.name,0);h.setAttribute("title",b.label,0);h.setAttribute("tabindex",b.tabIndex,0);b.disabled?(h.onclick=function(){},h.className="m-us-layout-storage-btn-none"):(h.onclick=b.onclick,b.device===w?(h.className="m-us-layout-storage-btn-on",h.focus()):h.className="m-us-layout-storage-btn-off");e.appendChild(h);
if("harddisk"!==b.name&&"webstorage"!==b.name){var d=document.createElement("span");d.className="m-us-drive-select";h.appendChild(d)}d=document.createElement("span");d.className="m-us-img-storage";var l=document.createElement("img");l.setAttribute("id","m-us-cert-manage-img-"+b.name,0);l.setAttribute("alt",b.label,0);b.disabled?l.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_"+b.name+"_d.png",0):l.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_"+b.name+
".png",0);d.appendChild(l);h.appendChild(d);d=document.createElement("span");d.setAttribute("id","m-us-cert-manage-lbl-"+b.name,0);d.className="m-us-layout-lbl-storage";d.appendChild(document.createTextNode(b.label));h.appendChild(d);e.appendChild(h);c.appendChild(e);return!0}function n(b,c,e){if("no_more"==e)a.uiUtil().msgBox(c.IDS_MSGBOX_NOT_MORE_MEDIA);else{b=document.getElementById("m-us-cert-manage-storage-wrap");"open"==e?(b.className="m-us-layout-storage-more-wrap",b=document.getElementById("m-us-cert-manage-storage-more-btn"),
b.setAttribute("title",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_HIDDEN+c.IDS_BUTTON,0),b.onclick=function(){n(this,c,"close")},b=document.getElementById("m-us-cert-manage-storage-more-btn-img"),b.setAttribute("alt",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_HIDDEN,0),b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_more_btn_close.png",0)):(b.className="m-us-layout-storage-wrap",b=document.getElementById("m-us-cert-manage-storage-more-btn"),b.setAttribute("title",
c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_SHOW+c.IDS_BUTTON,0),b.onclick=function(){n(this,c,"open")},b=document.getElementById("m-us-cert-manage-storage-more-btn-img"),b.setAttribute("alt",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_SHOW,0),b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_more_btn_open.png",0));b=a.ESVS.Media.list.split("|");for(var h=0;h<b.length;h++){var d=a.CONST.medias[b[h]];if(void 0!=d&&null!=d){var l=document.getElementById("m-us-cert-manage-storage-btn-li-"+
d.name);if(void 0!=l&&null!=l){var k=l.getAttribute("mediaIndex");"open"==e?(l.style.display="block",l.style.visibility="visible"):4<k?(l.style.display="none",l.style.visibility="hidden"):(l.style.display="block",l.style.visibility="visible");1==k&&document.getElementById("m-us-cert-manage-btn-"+d.name).focus()}}}}return!0}var u=function(){var b;b=window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("MSXML2.XMLHTTP.3.0");b.open("GET",a.ESVS.SRCPath+"unisignweb/rsrc/layout/mobile/m_certmanage.html?version="+
a.ver,!1);b.send(null);return b.responseText},v=function(){var b;b=window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("MSXML2.XMLHTTP.3.0");b.open("GET",a.ESVS.SRCPath+"unisignweb/rsrc/lang/certmanage_"+a.ESVS.Language+".js?version="+a.ver,!1);b.send(null);return b.responseText},y=eval(eval(v)()),x=null,k=null,q=a.ESVS.TabIndex,w=a.CONST.__PF_M_LS.device,p=window.console||{log:function(){}};return function(){var b=eval(u),c=eval(eval(v)());a.ESVS.TargetObj.innerHTML=b();document.getElementById("m-us-cert-manage-lbl-title").appendChild(document.createTextNode(c.IDS_CERT_MANAGEMENT));
for(var b=0,e=a.ESVS.Media.list.split("|"),h=0;h<e.length;h++){var d=a.CONST.medias[e[h]];if(null!=d&&void 0!=d){switch(d.device){case a.CONST.__PF_M_LS.device:d.label=c.IDS_STORAGE_LS;d.disabled=1==a.ESVS.Mode;d.onclick=function(){if(this&&c){w=a.CONST.__PF_M_LS.device;a.certsList&&(a.certsList=null);k.redrawList(null,-1);var b=f(a.CONST.__PF_M_LS.device,0,c,"");0!=b?(a.uiUtil().errMsgBox(c.IDS_MSGBOX_COMMON_ERROR_GET_CERT,b),k.redrawList(null,0)):(b=m(c))?k.redrawList(b.list,b.list.length):k.redrawList(null,
0)}if(this){n(this,y,"close");for(var b=a.ESVS.Media.list.split("|"),d=0;d<b.length;d++){var e=a.CONST.medias[b[d]];void 0!=e&&null!=e&&(e=document.getElementById("m-us-cert-manage-btn-"+e.name),void 0!=e&&null!=e&&"m-us-layout-storage-btn-none"!=e.className&&(this===e?(e.className="m-us-layout-storage-btn-on",e.focus()):e.className="m-us-layout-storage-btn-off"))}}};break;case a.CONST.__PF_M_TOUCHSIGN.device:d.label=c.IDS_STORAGE_TOUCHSIGN;d.disabled=!0;d.onclick=function(){};break;case a.CONST.__PF_M_SMARTSIGN.device:d.label=
c.IDS_STORAGE_SMARTSIGN;d.disabled=!0;d.onclick=function(){};break;case a.CONST.__PF_M_WEBSECTOKEN.device:d.label=c.IDS_STORAGE_WEBSECTOKEN;d.disabled=!0;d.onclick=function(){};break;case a.CONST.__PF_M_WEBSOFTTOKEN.device:d.label=c.IDS_STORAGE_WEBSOFTTOKEN;d.disabled=!0;d.onclick=function(){};break;default:d.label=c.IDS_STORAGE_ETC,d.disabled=!0,d.onclick=function(){}}d.tabIndex=q;d.mediaIndex=b+1;d.visibility=4<d.mediaIndex?"hidden":"visible";t(d)&&(q++,b++)}}e=document.getElementById("m-us-cert-manage-storage-more-btn");
null!=e&&void 0!=e&&(e.setAttribute("title",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_SHOW+c.IDS_BUTTON,0),4<b?(e.style.display="block",e.style.visibility="visible",e.setAttribute("tabindex",q++,0),e.onclick=function(){n(this,c,"open")}):(e.setAttribute("disabled","disabled",0),e.style.display="none",e.style.visibility="hidden",e.onclick=function(){n(this,c,"no_more")}),b=document.getElementById("m-us-cert-manage-storage-more-btn-img"),b.setAttribute("alt",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_SHOW,
0),b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_more_btn_open.png",0));z(c);b=document.getElementById("m-us-cert-manage-sub-get-cert-btn");b.setAttribute("value",c.IDS_CERT_GET,0);b.setAttribute("title",c.IDS_CERT_GET+c.IDS_BUTTON,0);b.setAttribute("tabindex",q++,0);b.onclick=function(){if(this&&c)try{var b="default";"android"===a.osName?"android samsung"===a.browserName||"android lg"===a.browserName||"android browser"===a.browserName?b="default":"android chrome"===a.browserName&&
(b="chrome"):"ios"==a.osName&&("ios safari"===a.browserName?b="default":"ios chrome"===a.browserName&&(b="googlechrome"));var d=window.location.href.split(/[?#]/)[0],e=d.lastIndexOf("/"),d=d.substr(0,e+1)+a.ESVS.SRCPath+"unisignweb/rsrc/layout/mobile/w2a/m_importcertresult.html";UniSignW2A.backupLoad(d,b,"0","recall")}catch(h){alert("failure\ne : "+h)}};b=document.getElementById("m-us-cert-manage-sw-info-btn");b.setAttribute("value",c.IDS_SW_INFO,0);b.setAttribute("title",c.IDS_SW_INFO+c.IDS_BUTTON,
0);b.setAttribute("tabindex",q++,0);b.onclick=function(){s(this)};document.getElementById("m-us-cert-manage-lbl-notice").appendChild(document.createTextNode(c.IDS_NOTICE));b=document.getElementById("m-us-cert-manage-cls-img-btn");b.setAttribute("tabindex",q++,0);b.onclick=function(){g.onCancel()};b=document.getElementById("m-us-cert-manage-cls-btn-img");b.setAttribute("alt",c.IDS_CLOSE_CERT_MANAGEMENT_CLOSE,0);b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_cert_close_btn.png",0);
return document.getElementById("m-us-div-cert-manage")}()};return function(g){var m=A({type:g.type,args:g.args,onConfirm:g.onConfirm,onCancel:g.onCancel});g=a.uiLayerLevel;var f=a.uiUtil().getOverlay(g);m.style.zIndex=g+1;document.body.insertBefore(f,document.body.firstChild);var s=window.onorientationchange;return{show:function(){f.style.display="block";var g=a.uiUtil().getNumSize(a.uiUtil().getStyle(m,"height","height")),g=-1===g?a.uiUtil().getScrollTop()+a.uiUtil().getViewportHeight()/6:a.uiUtil().getScrollTop()+
(a.uiUtil().getViewportHeight()-g)/3;m.style.top=0>g?"0px":g+"px";m.style.left=a.uiUtil().getScrollLeft()+(a.uiUtil().getViewportWidth()-a.uiUtil().getNumSize(a.uiUtil().getStyle(m,"width","width")))/2+"px";m.style.display="block";var t=0,n=0,u=0,v=0;0==window.orientation||180==window.orientation?(t=a.uiUtil().getViewportWidth(),n=a.uiUtil().getViewportHeight()):(u=a.uiUtil().getViewportWidth(),v=a.uiUtil().getViewportHeight());window.addEventListener("orientationchange",function(){var f=0,g=0;"android chrome"==
a.browserName||"unknown"==a.browserName?0==window.orientation||180==window.orientation?0<t?(f=t,g=n):(f=v+87,g=u-40):0<u?(f=u,g=v):(f=n+87,g=t-40):(f=a.uiUtil().getViewportWidth(),g=a.uiUtil().getViewportHeight());var k=a.uiUtil().getNumSize(a.uiUtil().getStyle(m,"width","width"));-1<k&&(f=a.uiUtil().getScrollLeft()+(f-k)/2+"px",m.style.left=f);f=a.uiUtil().getNumSize(a.uiUtil().getStyle(m,"height","height"));g=-1===f?a.uiUtil().getScrollTop()+g/6:a.uiUtil().getScrollTop()+(g-f)/3;m.style.top=g+"px";
s&&s()});a.uiLayerLevel+=10;a.ESVS.TabIndex+=30;setTimeout(function(){for(var f=a.ESVS.Media.list.split("|"),g=0;g<f.length;g++){var k=a.CONST.medias[f[g]];if(void 0!=k&&null!=k&&(k=document.getElementById("m-us-cert-manage-btn-"+k.name),void 0!=k&&null!=k)){k.focus();break}}},10)},hide:function(){f.style.display="none";m.style.display="none"},dispose:function(){window.addEventListener("orientationchange",function(){s&&s()});m.parentNode.removeChild(m);f.parentNode.removeChild(f);a.uiLayerLevel-=
10;a.ESVS.TabIndex-=30}}}};
