var __certselect=function(a){var D=function(f){function k(b){if(!a.certsList||!b)return null;var c=null,c=a.certsList,d=c.list.length,g=[],e=0,h=f.args.dn,m=null;null!=a.ESVS.Policy&&(-1!=a.ESVS.Policy.indexOf("|")?m=a.ESVS.Policy.split("|"):(m=[],m[0]=a.ESVS.Policy));var n=null;null!=a.ESVS.Organization&&(-1!=a.ESVS.Organization.indexOf("|")?n=a.ESVS.Organization.split("|"):(n=[],n[0]=a.ESVS.Organization));for(var l=0;l<d;l++){a.usWebToolkit.x509Certificate.parser(c.list[l].cert,"Base64");var B=
a.usWebToolkit.x509Certificate.getCertificatePoliciesOid(),k=a.usWebToolkit.x509Certificate.getSubjectName(),C=a.usWebToolkit.x509Certificate.getNotAfter(),q=a.usWebToolkit.x509Certificate.getNotAfter(),y=c.list[l].index,r=a.certUtil().getIssuerName(B);"undefined"==r&&(r=a.certUtil().getO(k));if(null==h||"DIGITAL_SIGNATURE_P1"!=f.type&&"DIGITAL_SIGNATURE_P7"!=f.type&&"DIGITAL_SIGNATURE_P7_EXT"!=f.type||k.toLowerCase()==h.toLowerCase()){if(null!=a.ESVS.Policy){for(var p=0;p<m.length&&m[p]!=B;p++);
if(m.length<=p)continue}if(null!=a.ESVS.Organization&&("CERT_RENEWAL"==f.type||"CERT_REVOCATION"==f.type||"CERT_SOE"==f.type)){for(p=0;p<n.length&&n[p].toLowerCase()!=a.certUtil().getO(k).toLowerCase();p++);if(n.length<=p)continue}if(a.ESVS.ShowExpiredCerts||"DIGITAL_SIGNATURE_P1"!=f.type&&"DIGITAL_SIGNATURE_P7"!=f.type&&"DIGITAL_SIGNATURE_P7_EXT"!=f.type||2!==a.certUtil().getExpirationStateValue(q))p=[],p[0]=a.certUtil().getCertType(B),p[1]=b.IDS_CERT_EXPIRATION_DAY+" ",p[2]=a.certUtil().getLocalDate(C),
p[3]=a.certUtil().getCN(k),p[4]=r,p[5]=y,p[6]=a.certUtil().getExpirationStateValue(q),g[e++]=p}}return c={list:g}}function s(b,c,d,g){if(a.CONST.__USFB_M_DISK.device>b||0>c||!d)return-1;d=c=0;a.certsList&&(a.certsList=null);if(a.CONST.__PF_M_LS.device===b&&2&a.ESVS.Mode){if(!a.PFSH)return-1;try{a.PFSH.SelectStorage(1)}catch(e){q.log("***** Plugin Free SelectStorage error *****"),q.log("e.code : ",e.code,"e.message : ",e.message,"e.detail : ",e.detail)}try{a.PFSH.LoadAllCerts(document.domain)}catch(h){301E5===
h.code?(a.PFSH.InstallCACerts(document.domain),a.PFSH.LoadAllCerts(document.domain)):(q.log("***** Plugin Free LoadAllCerts error *****"),q.log("e.code : ",h.code,"e.message : ",h.message,"e.detail : ",h.detail))}b=null;try{b=a.PFSH.GetUserCerts(document.domain),a.PFUC=b}catch(m){q.log("***** Plugin Free GetUserCerts error *****"),q.log("e.code : ",m.code,"e.message : ",m.message,"e.detail : ",m.detail)}b&&(c=b.length-1);q.log("***** Plugin Free *****");q.log("user certificate counts : ",c);if(0<
c){g=[];for(var n=0;n<c;n++){var f=n+1,l={};l.index=f;l.cert=b[f].signcert;g[n]=l}a.certsList={list:g}}else a.certsList=null,d=0}return d}function u(b,c,d){if(null==c||0>=c.length||null==d)return!1;a.certsList&&(a.certsList=null);if(0<b){var g=[],e={},h=null;e.index=b;e.cert=a.plugin().GetUserSignCertFromCertList(b);g[0]=e;a.certsList={list:g};if(h=k(d))return r.redrawList(h.list,h.list.length),FillPWBox(c),!0}else switch(b=a.plugin().GetLastErrorCode(),c=a.plugin().GetLastErrorMessage(),q.log("***** GetCertFromPFX *****"),
q.log("Err Code : ",b,"\nErr Msg : ",c),b){case 4301E4:a.uiUtil().msgBox(d.IDS_MSGBOX_PW_ERROR_PASSWORD_IS_NOT_MATCHED);break;default:a.uiUtil().errMsgBox(d.IDS_MSGBOX_COMMON_ERROR_GET_CERT,b)}a.certsList&&(a.certsList=null);r.redrawList(null,-1);ClearPWBox();return!1}function G(b,c,d){if(null==b||0>=b.length||null==c||0>=c.length||null==d)return!1;var g=!1;a.plugin().valid?(b=a.plugin().GetPfxCertList(b,c),g=u(b,c,d)):a.uiUtil().msgBox(d.IDS_MSGBOX_PLUGIN_ERROR_UNLOAD);return g}function v(b,c,d){if(null==
b||0>=b.length||null==c||0>=c.length||null==d)return!1;var g=!1;if(1&a.ESVS.Mode&&a.CONST.__PF_M_LS.device!==A)a.plugin().valid?(g=a.plugin().GetPfxCertListString(b,c),g=u(g,c,d)):a.uiUtil().msgBox(d.IDS_MSGBOX_PLUGIN_ERROR_UNLOAD);else a:if(b&&c&&d){var g=0,e={};try{var h=a.PFSH.SetP12OnMemory(b,c),g=h.index;a.PFUC=e=h.aluc}catch(m){q.log("***** Plugin Free SetP12OnMemory error *****");q.log("e.code : ",m.code,"e.message : ",m.message,"e.detail : ",m.detail);switch(m.code){case 1E7:0<=m.detail.indexOf("115010")?
a.uiUtil().msgBox(d.IDS_MSGBOX_PW_ERROR_PASSWORD_IS_NOT_MATCHED):a.uiUtil().errMsgBox(d.IDS_MSGBOX_COMMON_ERROR_GET_CERT,m.detail);break;default:a.uiUtil().errMsgBox(d.IDS_MSGBOX_COMMON_ERROR_GET_CERT,m.code)}g=!1;break a}a.certsList&&(a.certsList=null);b=[];var h={},n=null;h.index=g;h.cert=e[g].signcert;b[0]=h;a.certsList={list:b};(n=k(d))?(r.redrawList(n.list,n.list.length),FillPWBox(c),g=!0):(a.certsList=null,r.redrawList(null,-1),ClearPWBox(),g=!1)}else g=!1;return g}function w(b,c){if(null==
b||0>=b.length||null==c)return!1;if(0<b.length&&-1<b.indexOf(".")){var d=b.split("."),d=d[d.length-1].toLowerCase();if("pfx"!=d&&"p12"!=d)return a.uiUtil().msgBox(c.IDS_MSGBOX_FILE_ERROR_NOT_PFX),!1}else return a.uiUtil().msgBox(c.IDS_MSGBOX_FILE_ERROR_READ),!1;return!0}function x(b,c){if(!b||!c)return!1;var d=null,g=null,e=document.getElementById("m-us-confirm-btn"),h=document.getElementById("m-us-cert-search-btn");if("opera"==a.browserName||"safari"==a.browserName)b.style.display="none";if(window.FileReader){var m=
b.files;if(0<m.length){var n=m[0];if(!0==w(n.name,c)){var f=new FileReader;f.readAsBinaryString?(f.readAsBinaryString(n),f.addEventListener("load",function(){var b=f.result,d=b.length;if(n.size===d)g=a.usWebToolkit.util.encode64(b,d);else return a.uiUtil().msgBox(c.IDS_MSGBOX_FILE_ERROR_READ),!1})):(f.readAsArrayBuffer(n),f.addEventListener("load",function(){var b=f.result,d=null;try{var h=String.fromCharCode.apply(null,Array.prototype.slice.apply(new Uint8Array(b)));try{d=decodeURIComponent(escape(h))}catch(e){if(e instanceof
URIError)d=h;else throw e;}}catch(m){return a.uiUtil().msgBox(c.IDS_MSGBOX_FILE_ERROR_READ),!1}b=d.length;if(n.size===b)g=a.usWebToolkit.util.encode64(d,b);else return a.uiUtil().msgBox(c.IDS_MSGBOX_FILE_ERROR_READ),!1}))}else return setTimeout(function(){h.focus()},10),!1}else return setTimeout(function(){h.focus()},10),!1}else{if("msie"==a.browserName&&8===parseInt(a.browserVersion))m=document.getElementById("m-us-div-cert-select"),m.onselectstart=function(){return!0},b.select(),d=document.selection.createRange().text,
b.style.display="none",m.onselectstart=function(){return!1};else if("msie"==a.browserName&&9===parseInt(a.browserVersion)){if(d=b.value,-1<d.indexOf("fakepath"))return a.uiUtil().msgBox(c.IDS_MSGBOX_SEARCH_CERT_GUIDE_FOR_IE9),setTimeout(function(){h.focus()},10),!1}else d=b.value,q.log("file full path : ",d);if(!1==w(d,c))return setTimeout(function(){h.focus()},10),!1}Dialog=a.loadUI("password")({type:null,args:null,onConfirm:function(a){var b=!1,b=null!=d?G(d,a,c):v(g,a,c);a="";Dialog.dispose();
!0===b?setTimeout(function(){e.focus()},10):setTimeout(function(){h.focus()},10)},onCancel:function(){Dialog.dispose();setTimeout(function(){h.focus()},10)}});Dialog.show();return!0}function z(b){if(!b)return!1;var c=s(A,0,b,"");0!=c&&a.uiUtil().errMsgBox(b.IDS_MSGBOX_COMMON_ERROR_GET_CERT,c);c=k(b);E=a.loadUI("certlist");r=E({listtype:"mobilecertselect",bodyid:"m-us-div-list-inner",rowid:"m-us-mobile-cert-list-row",imgid:"m-us-mobile-cert-status-img",eleid:"m-us-mobile-cert-data-element",confirm:function(a,
c){if(b&&!(0>a||!c||1>c.length))if("DIGITAL_SIGNATURE_P7"===f.type)f.onConfirm(b.IDS_MSGBOX_SIGN_ERROR,a,c);else if("CERT_REVOCATION"===f.type)f.onConfirm(b.IDS_CONFIRMBOX_CERT_REVOCATION,a,c);else if("VID_VERIFICATION"===f.type)f.onConfirm(a,c,b.IDS_MSGBOX_VID_SUCCESS_VERIFICATION,b.IDS_MSGBOX_VID_ERROR_VERIFICATION,"PFS");else f.onConfirm()},cancel:function(){f.onCancel()}});c?r.drawList(c.list,c.list.length,t++):r.drawList(null,0,t++);return!0}function C(b){if(null==b||void 0==b)return!1;var c=
!a.uiUtil().isItSupportingThisStorage(b);!1==c&&null!=a.ESVS.Media&&null!=a.ESVS.Media.list&&0>a.ESVS.Media.list.indexOf(b.name)&&(c=!0);if(c)return!1;var c=document.getElementById("m-us-storage-btn-list"),d=document.createElement("li");d.setAttribute("id","m-us-storage-btn-li-"+b.name,0);d.setAttribute("mediaIndex",b.mediaIndex,0);5==b.mediaIndex&&(d.className="line-first");"hidden"===b.visibility?(d.style.display="none",d.style.visibility="hidden"):(d.style.display="block",d.style.visibility="visible");
var g=document.createElement("button");g.setAttribute("type","button",0);g.setAttribute("id","m-us-btn-"+b.name,0);g.setAttribute("title",b.label,0);g.setAttribute("tabindex",b.tabIndex,0);b.disabled?(g.onclick=function(){},g.className="m-us-layout-storage-btn-none"):(g.onclick=b.onclick,b.device===A?(g.className="m-us-layout-storage-btn-on",g.focus()):g.className="m-us-layout-storage-btn-off");d.appendChild(g);if("harddisk"!==b.name&&"webstorage"!==b.name){var e=document.createElement("span");e.className=
"m-us-drive-select";g.appendChild(e)}e=document.createElement("span");e.className="m-us-img-storage";var h=document.createElement("img");h.setAttribute("id","m-us-img-"+b.name,0);h.setAttribute("alt",b.label,0);b.disabled?h.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_"+b.name+"_d.png",0):h.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_"+b.name+".png",0);e.appendChild(h);g.appendChild(e);e=document.createElement("span");e.setAttribute("id","m-us-lbl-"+
b.name,0);e.className="m-us-layout-lbl-storage";e.appendChild(document.createTextNode(b.label));g.appendChild(e);d.appendChild(g);c.appendChild(d);return!0}function l(b,c,d){if("no_more"==d)a.uiUtil().msgBox(c.IDS_MSGBOX_NOT_MORE_MEDIA);else{b=document.getElementById("m-us-storage-wrap");"open"==d?(b.className="m-us-layout-storage-more-wrap",b=document.getElementById("m-us-storage-more-btn"),b.setAttribute("title",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_HIDDEN+c.IDS_BUTTON,0),b.onclick=function(){l(this,
c,"close")},b=document.getElementById("m-us-storage-more-btn-img"),b.setAttribute("alt",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_HIDDEN,0),b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_more_btn_close.png",0)):(b.className="m-us-layout-storage-wrap",b=document.getElementById("m-us-storage-more-btn"),b.setAttribute("title",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_SHOW+c.IDS_BUTTON,0),b.onclick=function(){l(this,c,"open")},b=document.getElementById("m-us-storage-more-btn-img"),
b.setAttribute("alt",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_SHOW+c.IDS_BUTTON,0),b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_more_btn_open.png",0));b=a.ESVS.Media.list.split("|");for(var g=0;g<b.length;g++){var e=a.CONST.medias[b[g]];if(void 0!=e&&null!=e){var h=document.getElementById("m-us-storage-btn-li-"+e.name);if(void 0!=h&&null!=h){var f=h.getAttribute("mediaIndex");"open"==d?(h.style.display="block",h.style.visibility="visible"):4<f?(h.style.display="none",
h.style.visibility="hidden"):(h.style.display="block",h.style.visibility="visible");1==f&&document.getElementById("m-us-btn-"+e.name).focus()}}}}return!0}var y=function(){var b;b=window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("MSXML2.XMLHTTP.3.0");b.open("GET",a.ESVS.SRCPath+("unisignweb/rsrc/layout/mobile/m_certselect.html?version="+a.ver),!1);b.send(null);return b.responseText},F=function(){var b;b=window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("MSXML2.XMLHTTP.3.0");
b.open("GET",a.ESVS.SRCPath+"unisignweb/rsrc/lang/certselect_"+a.ESVS.Language+".js?version="+a.ver,!1);b.send(null);return b.responseText},D=eval(eval(F)()),E=null,r=null,t=a.ESVS.TabIndex,A=a.CONST.__PF_M_LS.device,q=window.console||{log:function(){}};return function(){var b=eval(y),c=eval(eval(F)());a.ESVS.TargetObj.innerHTML=b();document.getElementById("m-us-lbl-title").appendChild(document.createTextNode(c.IDS_CERT_SELECTION));for(var b=0,d=a.ESVS.Media.list.split("|"),g=0;g<d.length;g++){var e=
a.CONST.medias[d[g]];if(null!=e&&void 0!=e){switch(e.device){case a.CONST.__PF_M_LS.device:e.label=c.IDS_STORAGE_LS;e.disabled=1==a.ESVS.Mode;e.onclick=function(){if(this&&c){A=a.CONST.__PF_M_LS.device;a.certsList&&(a.certsList=null);r.redrawList(null,-1);var b=s(a.CONST.__PF_M_LS.device,0,c,"");0!=b?(a.uiUtil().errMsgBox(c.IDS_MSGBOX_COMMON_ERROR_GET_CERT,b),r.redrawList(null,0)):(b=k(c))?r.redrawList(b.list,b.list.length):r.redrawList(null,0)}if(this){l(this,D,"close");for(var b=a.ESVS.Media.list.split("|"),
d=0;d<b.length;d++){var e=a.CONST.medias[b[d]];void 0!=e&&null!=e&&(e=document.getElementById("m-us-btn-"+e.name),void 0!=e&&null!=e&&"m-us-layout-storage-btn-none"!=e.className&&(this===e?(e.className="m-us-layout-storage-btn-on",e.focus()):e.className="m-us-layout-storage-btn-off"))}}};break;case a.CONST.__PF_M_TOUCHSIGN.device:e.label=c.IDS_STORAGE_TOUCHSIGN;e.disabled=!0;e.onclick=function(){};break;case a.CONST.__PF_M_SMARTSIGN.device:e.label=c.IDS_STORAGE_SMARTSIGN;e.disabled=!0;e.onclick=function(){};
break;case a.CONST.__PF_M_WEBSECTOKEN.device:e.label=c.IDS_STORAGE_WEBSECTOKEN;e.disabled=!0;e.onclick=function(){};break;case a.CONST.__PF_M_WEBSOFTTOKEN.device:e.label=c.IDS_STORAGE_WEBSOFTTOKEN;e.disabled=!0;e.onclick=function(){};break;default:e.label=c.IDS_STORAGE_ETC,e.disabled=!0,e.onclick=function(){}}e.tabIndex=t;e.mediaIndex=b+1;e.visibility=4<e.mediaIndex?"hidden":"visible";C(e)&&(t++,b++)}}d=document.getElementById("m-us-storage-more-btn");null!=d&&void 0!=d&&(d.setAttribute("title",c.IDS_STORAGE_MORE_VIEW+
c.IDS_STORAGE_MORE_VIEW_SHOW+c.IDS_BUTTON,0),4<b?(d.style.display="block",d.style.visibility="visible",d.setAttribute("tabindex",t++,0),d.onclick=function(){l(this,c,"open")}):(d.setAttribute("disabled","disabled",0),d.style.display="none",d.style.visibility="hidden",d.onclick=function(){l(this,c,"no_more")}),b=document.getElementById("m-us-storage-more-btn-img"),b.setAttribute("alt",c.IDS_STORAGE_MORE_VIEW+c.IDS_STORAGE_MORE_VIEW_SHOW,0),b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_more_btn_open.png",
0));z(c);document.getElementById("m-us-file-search-hidden").onchange=function(){x(this,c)};b=document.getElementById("m-us-cert-search-btn");b.setAttribute("value",c.IDS_CERT_SEARCH,0);b.setAttribute("title",c.IDS_CERT_SEARCH+c.IDS_BUTTON,0);b.setAttribute("tabindex",t++,0);b.onclick=function(){if(null!=c){var b=document.getElementById("m-us-file-search-hidden");if("safari"==a.browserName&&6>parseFloat(a.browserVersion))a.uiUtil().msgBox(c.IDS_MSGBOX_SEARCH_CERT_GUIDE_FOR_SAFARI);else{if("opera"==
a.browserName||"safari"==a.browserName||"msie"==a.browserName&&8===parseInt(a.browserVersion))b.style.display="block";b.value="";if(""!=b.value){var d=b.onchange,e=b.parentNode;e.removeChild(b);b=document.createElement("input");b.setAttribute("type","file",0);b.setAttribute("accept","application/x-pkcs12",0);b.setAttribute("id","m-us-file-search-hidden",0);b.className="m-us-layout-file-search-hidden";b.onchange=d;e.appendChild(b)}b.click()}}};b.readOnly=!0;b.disabled=!0;b=document.getElementById("m-us-cert-proposal-btn");
b.setAttribute("value",c.IDS_CERT_PROPOSAL,0);b.setAttribute("title",c.IDS_CERT_PROPOSAL+c.IDS_BUTTON,0);b.setAttribute("tabindex",t++,0);b.onclick=function(){this&&("firefox"==a.browserName?window.open("https://raadmin.crosscert.com/customer/tk/Main.jsp?","crosscert_url","scrollbars=1"):window.open("https://raadmin.crosscert.com/customer/tk/Main.jsp?"),this.focus())};document.getElementById("m-us-lbl-notice").appendChild(document.createTextNode(c.IDS_NOTICE));b=document.getElementById("m-us-cls-img-btn");
b.setAttribute("tabindex",t++,0);b.onclick=function(){f.onCancel()};b=document.getElementById("m-us-cls-btn-img");b.setAttribute("alt",c.IDS_CLOSE_CERT_SELECTION_CLOSE,0);b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_cert_close_btn.png",0);return document.getElementById("m-us-div-cert-select")}()};return function(f){var k=D({type:f.type,args:f.args,onConfirm:f.onConfirm,onCancel:f.onCancel});f=a.uiLayerLevel;var s=a.uiUtil().getOverlay(f);k.style.zIndex=f+1;document.body.insertBefore(s,
document.body.firstChild);var u=window.onorientationchange;return{show:function(){s.style.display="block";var f=a.uiUtil().getNumSize(a.uiUtil().getStyle(k,"height","height")),f=-1===f?a.uiUtil().getScrollTop()+a.uiUtil().getViewportHeight()/6:a.uiUtil().getScrollTop()+(a.uiUtil().getViewportHeight()-f)/3;k.style.top=0>f?"0px":f+"px";k.style.left=a.uiUtil().getScrollLeft()+(a.uiUtil().getViewportWidth()-a.uiUtil().getNumSize(a.uiUtil().getStyle(k,"width","width")))/2+"px";k.style.display="block";
var v=0,w=0,x=0,z=0;0==window.orientation||180==window.orientation?(v=a.uiUtil().getViewportWidth(),w=a.uiUtil().getViewportHeight()):(x=a.uiUtil().getViewportWidth(),z=a.uiUtil().getViewportHeight());window.addEventListener("orientationchange",function(){var f=0,l=0;"android chrome"==a.browserName||"unknown"==a.browserName?0==window.orientation||180==window.orientation?0<v?(f=v,l=w):(f=z+87,l=x-40):0<x?(f=x,l=z):(f=w+87,l=v-40):(f=a.uiUtil().getViewportWidth(),l=a.uiUtil().getViewportHeight());var y=
a.uiUtil().getNumSize(a.uiUtil().getStyle(k,"width","width"));-1<y&&(f=a.uiUtil().getScrollLeft()+(f-y)/2+"px",k.style.left=f);f=a.uiUtil().getNumSize(a.uiUtil().getStyle(k,"height","height"));l=-1===f?a.uiUtil().getScrollTop()+l/6:a.uiUtil().getScrollTop()+(l-f)/3;k.style.top=l+"px";u&&u()});a.uiLayerLevel+=10;a.ESVS.TabIndex+=30;setTimeout(function(){for(var f=a.ESVS.Media.list.split("|"),l=0;l<f.length;l++){var k=a.CONST.medias[f[l]];if(void 0!=k&&null!=k&&(k=document.getElementById("m-us-btn-"+
k.name),void 0!=k&&null!=k)){k.focus();break}}},10)},hide:function(){s.style.display="none";k.style.display="none"},dispose:function(){window.addEventListener("orientationchange",function(){u&&u()});k.parentNode.removeChild(k);s.parentNode.removeChild(s);a.uiLayerLevel-=10;a.ESVS.TabIndex-=30}}}};
