var __storageselect=function(a){var s=function(c){function q(b){if(!b)return alert("UI load error."),!1;if("CERT_STORAGE"===c.type)a.ESVS.TargetObj.innerHTML=b;else{var f=document.createElement("div");document.body.insertBefore(f,document.body.firstChild);f.innerHTML=b}return!0}function n(b){if(a.CONST.__USFB_M_DISK.device>h||(a.CONST.__USFB_M_DISK.device===h||a.CONST.__USFB_M_HSMKEY.device===h)&&1>l)return a.uiUtil().msgBox(b.IDS_MSGBOX_ERROR_PLEASE_SELECT_STORAGE),!1;if("CERT_COPY"==c.type&&c.args.sourceDevice===
h&&c.args.sourceDrive===l)return a.uiUtil().msgBox(b.IDS_MSGBOX_ERROR_WARNING_SAME_STORAGE),!1;if(("CERT_COPY"===c.type||"CERT_IMPORT"===c.type||"CERT_STORAGE"===c.type)&&a.CONST.__USFB_M_SMARTCARD.device===h&&0===l&&!confirm(b.IDS_CONFIRMBOX_WARNING_CHANGE_CERT))return!1;c.onConfirm(h,l);return!0}function g(b){if(null==b||void 0==b)return!1;var f=!a.uiUtil().isItSupportingThisStorage(b);!1==f&&null!=a.ESVS.Media&&null!=a.ESVS.Media.list&&0>a.ESVS.Media.list.indexOf(b.name)&&(f=!0);if(f)return!1;
var f=document.getElementById("m-us-btn-storage-btn-list"),k=document.createElement("li");k.setAttribute("id","m-us-storage-btn-li-"+b.name,0);k.setAttribute("mediaIndex",b.mediaIndex,0);5==b.mediaIndex&&(k.className="line-first");"hidden"===b.visibility?(k.style.display="none",k.style.visibility="hidden"):(k.style.display="block",k.style.visibility="visible");var d=document.createElement("button");d.setAttribute("type","button",0);d.setAttribute("id","m-us-btn-storage-"+b.name,0);d.setAttribute("title",
b.label,0);d.setAttribute("tabindex",b.tabIndex,0);b.disabled?(d.onclick=function(){},d.className="m-us-layout-storage-btn-none"):(d.onclick=b.onclick,b.device===h?(d.className="m-us-layout-storage-btn-on",d.focus()):d.className="m-us-layout-storage-btn-off");k.appendChild(d);if("harddisk"!==b.name&&"webstorage"!==b.name){var e=document.createElement("span");e.className="m-us-drive-select";d.appendChild(e)}e=document.createElement("span");e.className="m-us-img-storage";var c=document.createElement("img");
c.setAttribute("id","m-us-img-storage-"+b.name,0);c.setAttribute("alt",b.label,0);b.disabled?c.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_"+b.name+"_d.png",0):c.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_media_"+b.name+".png",0);e.appendChild(c);d.appendChild(e);e=document.createElement("span");e.setAttribute("id","m-us-lbl-storage-"+b.name,0);e.className="m-us-layout-lbl-storage";e.appendChild(document.createTextNode(b.label));d.appendChild(e);k.appendChild(d);
f.appendChild(k);return!0}var p=function(){var b;b=window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("MSXML2.XMLHTTP.3.0");b.open("GET",a.ESVS.SRCPath+"unisignweb/rsrc/layout/mobile/m_storageselect.html?version="+a.ver,!1);b.send(null);return b.responseText},r=function(){var b;b=window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("MSXML2.XMLHTTP.3.0");b.open("GET",a.ESVS.SRCPath+"unisignweb/rsrc/lang/storageselect_"+a.ESVS.Language+".js?version="+a.ver,!1);b.send(null);
return b.responseText};eval(eval(r)());var m=a.ESVS.TabIndex,h=a.CONST.__USFB_M_DISK.device,l=0,h=a.CONST.__PF_M_LS.device;return function(){var b=eval(p),f=eval(eval(r)());q(b());document.getElementById("m-us-storage-select-lbl-title").appendChild(document.createTextNode(f.IDS_STORAGE_SELECTION));b=document.getElementById("m-us-storage-select-cls-btn-img");b.setAttribute("alt",f.IDS_STORAGE_SELECTION_CLOSE,0);b.setAttribute("src",a.ESVS.SRCPath+"unisignweb/rsrc/img/mobile/m_x-btn.png",0);b=document.getElementById("m-us-storage-select-notice-lbl");
"CERT_STORAGE"===c.type?b.appendChild(document.createTextNode(f.IDS_SAVE_NOTICE)):b.appendChild(document.createTextNode(f.IDS_COPY_NOTICE));for(var b=0,k=a.ESVS.Media.list.split("|"),d=0;d<k.length;d++){var e=a.CONST.medias[k[d]];if(void 0!=e&&null!=e){switch(e.device){case a.CONST.__PF_M_LS.device:e.label=f.IDS_STORAGE_LS;e.disabled=1==a.ESVS.Mode||"CERT_COPY"==c.type;e.onclick=function(){this&&f&&(this.focus(),h=a.CONST.__PF_M_LS.device,n(f));if(this)for(var b=a.ESVS.Media.list.split("|"),e=0;e<
b.length;e++){var d=a.CONST.medias[b[e]];void 0!=d&&null!=d&&(d=document.getElementById("m-us-btn-storage-"+d.name),void 0!=d&&null!=d&&"m-us-layout-storage-btn-none"!=d.className&&(this===d?(d.className="m-us-layout-storage-btn-on",d.focus()):d.className="m-us-layout-storage-btn-off"))}};break;case a.CONST.__PF_M_TOUCHSIGN.device:e.label=f.IDS_STORAGE_TOUCHSIGN;e.disabled=!0;e.onclick=function(){};break;case a.CONST.__PF_M_SMARTSIGN.device:e.label=f.IDS_STORAGE_SMARTSIGN;e.disabled=!0;e.onclick=
function(){};break;case a.CONST.__PF_M_WEBSECTOKEN.device:e.label=f.IDS_STORAGE_WEBSECTOKEN;e.disabled=!0;e.onclick=function(){};break;case a.CONST.__PF_M_WEBSOFTTOKEN.device:e.label=f.IDS_STORAGE_WEBSOFTTOKEN;e.disabled=!0;e.onclick=function(){};break;default:e.label=f.IDS_STORAGE_ETC,e.disabled=!0,e.onclick=function(){}}e.tabIndex=m;e.mediaIndex=b+1;e.visibility="visible";g(e)&&(m++,b++,1==b&&document.getElementById("m-us-btn-storage-"+e.name).focus())}}document.getElementById("m-us-storage-select-warning-lbl").appendChild(document.createTextNode(f.IDS_WARNING));
b=document.getElementById("m-us-storage-select-cancel-btn");b.setAttribute("value",f.IDS_CANCEL,0);b.setAttribute("title",f.IDS_CANCEL+f.IDS_BUTTON,0);b.setAttribute("tabindex",m++,0);b.onclick=function(){c.onCancel()};b=document.getElementById("m-us-storage-select-cls-img-btn");b.setAttribute("tabindex",m++,0);b.onclick=function(){c.onCancel()};return document.getElementById("m-us-div-storage-select")}()};return function(c){var q=a.uiLayerLevel,n=a.uiUtil().getOverlay(q),g=s({type:c.type,args:c.args,
onConfirm:c.onConfirm,onCancel:c.onCancel});g.style.zIndex=q+1;a.ESVS.TargetObj.insertBefore(n,a.ESVS.TargetObj.firstChild);var p=window.onorientationchange;return{show:function(){n.style.display="block";var c=a.uiUtil().getNumSize(a.uiUtil().getStyle(g,"height","height")),c=-1===c?a.uiUtil().getScrollTop()+a.uiUtil().getViewportHeight()/6:a.uiUtil().getScrollTop()+(a.uiUtil().getViewportHeight()-c)/3;g.style.top=0>c?"0px":c+"px";g.style.left=a.uiUtil().getScrollLeft()+(a.uiUtil().getViewportWidth()-
a.uiUtil().getNumSize(a.uiUtil().getStyle(g,"width","width")))/2+"px";g.style.display="block";var m=0,h=0,l=0,b=0;0==window.orientation||180==window.orientation?(m=a.uiUtil().getViewportWidth(),h=a.uiUtil().getViewportHeight()):(l=a.uiUtil().getViewportWidth(),b=a.uiUtil().getViewportHeight());window.addEventListener("orientationchange",function(){var f=0,c=0;"android chrome"==a.browserName||"unknown"==a.browserName?0==window.orientation||180==window.orientation?0<m?(f=m,c=h):(f=b+87,c=l-40):0<l?
(f=l,c=b):(f=h+87,c=m-40):(f=a.uiUtil().getViewportWidth(),c=a.uiUtil().getViewportHeight());var d=a.uiUtil().getNumSize(a.uiUtil().getStyle(g,"width","width"));-1<d&&(f=a.uiUtil().getScrollLeft()+(f-d)/2+"px",g.style.left=f);f=a.uiUtil().getNumSize(a.uiUtil().getStyle(g,"height","height"));c=-1===f?a.uiUtil().getScrollTop()+c/6:a.uiUtil().getScrollTop()+(c-f)/3;g.style.top=c+"px";p&&p()});a.uiLayerLevel+=10;a.ESVS.TabIndex+=30;setTimeout(function(){for(var b=a.ESVS.Media.list.split("|"),c=0;c<b.length;c++){var d=
a.CONST.medias[b[c]];if(void 0!=d&&null!=d&&(d=document.getElementById("m-us-btn-storage-"+d.name),void 0!=d&&null!=d)){d.focus();break}}},10)},hide:function(){n.style.display="none";g.style.display="none"},dispose:function(){window.addEventListener("orientationchange",function(){p&&p()});"CERT_STORAGE"===c.type?g.parentNode.removeChild(g):g.parentNode.parentNode.removeChild(g.parentNode);n.parentNode.removeChild(n);a.uiLayerLevel-=10;a.ESVS.TabIndex-=30}}}};
